src/Entity/AssessmentModule/Configuration/GeneralConfiguration.php
<?php

namespace App\Entity\AssessmentModule\Configuration;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity
 * @ORM\Table(name="AssessmentModule_GeneralConfiguration")
 */
class GeneralConfiguration
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }


    /**
     * @ORM\Column(type="text")
     * Base URL of the website that is shown in the assessment frame
     */
    private $url;

    /**
     * @return mixed
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @param mixed $url
     */
    public function setUrl($url)
    {
        $this->url = $url;
    }

    /**
     * @ORM\Column(type="string")
     * Presentation mode for the assessment documents. Either via an iframe, image URL, or simply document info (title, author, abstract, keywords)
     */
    private $presentation_mode;

    /**
     * @return mixed
     */
    public function getPresentationMode()
    {
        return $this->presentation_mode;
    }

    /**
     * @param mixed $presentation_mode
     */
    public function setPresentationMode($presentation_mode)
    {
        $this->presentation_mode = $presentation_mode;
    }


    /**
     * @ORM\Column(type="integer")
     * Fields that are shown in assessment frontend if iframe not selected
     */
    private $presentationFields;

    /**
     * @return mixed
     */
    public function getPresentationFields()
    {
        return $this->presentationFields;
    }

    /**
     * @param mixed $presentationFields
     */
    public function setPresentationFields($presentationFields)
    {
        $this->presentationFields = $presentationFields;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     * Name for the first presentation field
     */
    private $presentation_field_name_1;

    /**
     * @return mixed
     */
    public function getPresentationFieldName1()
    {
        return $this->presentation_field_name_1;
    }

    /**
     * @param $presentation_field_name
     */
    public function setPresentationFieldName1($presentation_field_name)
    {
        $this->presentation_field_name_1 = $presentation_field_name;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     * Name for the second presentation field
     */
    private $presentation_field_name_2;

    /**
     * @return mixed
     */
    public function getPresentationFieldName2()
    {
        return $this->presentation_field_name_2;
    }

    /**
     * @param $presentation_field_name
     */
    public function setPresentationFieldName2($presentation_field_name)
    {
        $this->presentation_field_name_2 = $presentation_field_name;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     * Name for the third presentation field
     */
    private $presentation_field_name_3;

    /**
     * @return mixed
     */
    public function getPresentationFieldName3()
    {
        return $this->presentation_field_name_3;
    }

    /**
     * @param $presentation_field_name
     */
    public function setPresentationFieldName3($presentation_field_name)
    {
        $this->presentation_field_name_3 = $presentation_field_name;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     * Name for the fourth presentation field
     */
    private $presentation_field_name_4;

    /**
     * @return mixed
     */
    public function getPresentationFieldName4()
    {
        return $this->presentation_field_name_4;
    }

    /**
     * @param $presentation_field_name
     */
    public function setPresentationFieldName4($presentation_field_name)
    {
        $this->presentation_field_name_4 = $presentation_field_name;
    }


    /**
     * @ORM\Column(type="text", nullable=true)
     * If only queries, only topics, or both is used
     */
    private $query_style;

    /**
     * @return mixed
     */
    public function getQueryStyle()
    {
        return $this->query_style;
    }

    /**
     * @param mixed $query_style
     */
    public function setQueryStyle($query_style)
    {
        $this->query_style = $query_style;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     * Name for the query heading
     */
    private $queryHeadingName;

    /**
     * @return mixed
     */
    public function getQueryHeadingName()
    {
        return $this->queryHeadingName;
    }

    /**
     * @param $queryHeadingName
     */
    public function setQueryHeadingName($queryHeadingName)
    {
        $this->queryHeadingName = $queryHeadingName;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     * Name for the topic heading
     */
    private $topicHeadingName;

    /**
     * @return mixed
     */
    public function getTopicHeadingName()
    {
        return $this->topicHeadingName;
    }

    /**
     * @param $topicHeadingName
     */
    public function setTopicHeadingName($topicHeadingName)
    {
        $this->topicHeadingName = $topicHeadingName;
    }


    /**
     * @ORM\Column(type="boolean")
     * If document heading is used
     */
    private $documentHeading;

    /**
     * @return mixed
     */
    public function getDocumentHeading()
    {
        return $this->documentHeading;
    }

    /**
     * @param mixed $documentHeading
     */
    public function setDocumentHeading($documentHeading)
    {
        $this->documentHeading = $documentHeading;
    }


    /**
     * @ORM\Column(type="string", nullable=true)
     * Name for the document heading
     */
    private $documentHeadingName;

    /**
     * @return mixed
     */
    public function getDocumentHeadingName()
    {
        return $this->documentHeadingName;
    }

    /**
     * @param $documentHeadingName
     */
    public function setDocumentHeadingName($documentHeadingName)
    {
        $this->documentHeadingName = $documentHeadingName;
    }


    /**
     * @ORM\Column(type="boolean", nullable=true)
     * Random presentation of query/document combinations or grouping by query
     * (i.e., all documents for a query are display one after another)
     */
    private $group_by;

    /**
     * @return mixed
     */
    public function getGroupBy()
    {
        return $this->group_by;
    }

    /**
     * @param mixed $group_by
     */
    public function setGroupBy($group_by)
    {
        $this->group_by = $group_by;
    }


    /**
     * @ORM\Column(type="string")
     * Random presentation of query/document combinations or grouping by query
     * (i.e., all documents for a query are display one after another)
     */
    private $group_by_category;

    /**
     * @return mixed
     */
    public function getGroupByCategory()
    {
        return $this->group_by_category;
    }

    /**
     * @param mixed $group_by_category
     */
    public function setGroupByCategory($group_by_category)
    {
        $this->group_by_category = $group_by_category;
    }


    /**
     * @ORM\Column(type="boolean")
     * Defines whether documents can be skipped
     */
    private $skipping_allowed;

    /**
     * @return mixed
     */
    public function getSkippingAllowed()
    {
        return $this->skipping_allowed;
    }

    /**
     * @param mixed $skipping_allowed
     */
    public function setSkippingAllowed($skipping_allowed)
    {
        $this->skipping_allowed = $skipping_allowed;
    }


    /**
     * @ORM\Column(type="text", nullable=true)
     * Defines how documents can be skipped. "reject", "postpone", "both"
     */
    private $skipping_options;

    /**
     * @return mixed
     */
    public function getSkippingOptions()
    {
        return $this->skipping_options;
    }

    /**
     * @param mixed $skipping_options
     */
    public function setSkippingOptions($skipping_options)
    {
        $this->skipping_options = $skipping_options;
    }


    /**
     * @ORM\Column(type="boolean", nullable=true)
     * Defines if comments are allowed when skipping documents
     */
    private $skipping_comment;

    /**
     * @return mixed
     */
    public function getSkippingComment()
    {
        return $this->skipping_comment;
    }

    /**
     * @param mixed $skipping_comment
     */
    public function setSkippingComment($skipping_comment)
    {
        $this->skipping_comment = $skipping_comment;
    }


    /**
     * @ORM\Column(type="boolean")
     * Defines whether a button appears that allows to load a new document without skipping or postponing the old one
     */
    private $loading_new_document;

    /**
     * @return mixed
     */
    public function getLoadingNewDocument()
    {
        return $this->loading_new_document;
    }

    /**
     * @param mixed $loading_new_document
     */
    public function setLoadingNewDocument($loading_new_document)
    {
        $this->loading_new_document = $loading_new_document;
    }


    /**
     * @ORM\Column(type="boolean")
     * Defines whether a user's progress bar is shown
     */
    private $user_progress_bar;

    /**
     * @return mixed
     */
    public function getUserProgressBar()
    {
        return $this->user_progress_bar;
    }

    /**
     * @param mixed $user_progress_bar
     */
    public function setUserProgressBar($user_progress_bar)
    {
        $this->user_progress_bar = $user_progress_bar;
    }


    /**
     * @ORM\Column(type="boolean")
     * Defines whether the total's progress bar is shown
     */
    private $total_progress_bar;

    /**
     * @return mixed
     */
    public function getTotalProgressBar()
    {
        return $this->total_progress_bar;
    }

    /**
     * @param mixed $total_progress_bar
     */
    public function setTotalProgressBar($total_progress_bar)
    {

src/Entity/ComparisonModule/Configuration/LiveConfiguration.php
<?php

namespace App\Entity\ComparisonModule\Configuration;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity
 * @ORM\Table(name="ComparisonModule_LiveConfiguration")
 */
class LiveConfiguration
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }


    /**
     * @ORM\Column(type="string", length=50)
     * Description of the evaluation buttons on the comparison page
     */
    private $evalButton_left;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $evalButton_right;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $middleButton;

    /**
     * @ORM\Column(type="boolean")
     * Set randomization to TRUE or FALSE
     */
    private $randomization;

    /**
     * @ORM\Column(type="boolean")
     * Set randomization to TRUE or FALSE
     */
    private $randomization_participation;

    /**
     * @ORM\Column(type="string", length=50)
     * Set cookie values
     */
    private $cookie_name;

    /**
     * @ORM\Column(type="smallint")
     */
    private $cookie_expires; // expire time in days

    /**
     * @ORM\Column(type="smallint")
     */
    private $participations_per_time_span; // number of maximum participations for a single user per time span

    /**
     * @ORM\Column(type="smallint")
     */
    private $time_span; // time span in hours


    /**
     * @ORM\Column(type="boolean")
     */
    private $allow_tie;

    /**
     * @return mixed
     */
    public function getAllowTie()
    {
        return $this->allow_tie;
    }

    /**
     * @param $allow_tie
     */
    public function setAllowTie($allow_tie)
    {
        $this->allow_tie = $allow_tie;
    }


    /**
     * @ORM\Column(type="boolean")
     */
    private $use_base_website;

    /**
     * @return mixed
     */
    public function getUseBaseWebsite()
    {
        return $this->use_base_website;
    }

    /**
     * @param $use_base_website
     */
    public function setUseBaseWebsite($use_base_website)
    {
        $this->use_base_website = $use_base_website;
    }


    /**
     * @ORM\Column(type="string")
     */
    private $document_order;

    /**
     * @return mixed
     */
    public function getDocumentOrder()
    {
        return $this->document_order;
    }

    /**
     * @param $document_order
     */
    public function setDocumentOrder($document_order)
    {
        $this->document_order = $document_order;
    }


    /**
     * @return mixed
     */
    public function getEvalButtonLeft()
    {
        return $this->evalButton_left;
    }

    /**
     * @param mixed $evalButton_left
     */
    public function setEvalButtonLeft($evalButton_left)
    {
        $this->evalButton_left = $evalButton_left;
    }

    /**
     * @return mixed
     */
    public function getEvalButtonRight()
    {
        return $this->evalButton_right;
    }

    /**
     * @param mixed $evalButton_right
     */
    public function setEvalButtonRight($evalButton_right)
    {
        $this->evalButton_right = $evalButton_right;
    }

    /**
     * @return mixed
     */
    public function getMiddleButton()
    {
        return $this->middleButton;
    }

    /**
     * @param mixed $middleButton
     */
    public function setMiddleButton($middleButton)
    {
        $this->middleButton = $middleButton;
    }

    /**
     * @return mixed
     */
    public function getRandomization()
    {
        return $this->randomization;
    }

    /**
     * @param mixed $randomization
     */
    public function setRandomization($randomization)
    {
        $this->randomization = $randomization;
    }

    /**
     * @return mixed
     */
    public function getRandomizationParticipation()
    {
        return $this->randomization_participation;
    }

    /**
     * @param mixed $randomization_participation
     */
    public function setRandomizationParticipation($randomization_participation)
    {
        $this->randomization_participation = $randomization_participation;
    }

    /**
     * @return mixed
     */
    public function getCookieName()
    {
        return $this->cookie_name;
    }

    /**
     * @param mixed $cookie_name
     */
    public function setCookieName($cookie_name)
    {
        $this->cookie_name = $cookie_name;
    }

    /**
     * @return mixed
     */
    public function getCookieExpires()
    {
        return $this->cookie_expires;
    }

    /**
     * @param mixed $cookie_expires
     */
    public function setCookieExpires($cookie_expires)
    {
        $this->cookie_expires = $cookie_expires;
    }

    /**
     * @return mixed
     */
    public function getParticipationsPerTimeSpan()
    {
        return $this->participations_per_time_span;
    }

    /**
     * @param mixed $participations_per_time_span
     */
    public function setParticipationsPerTimeSpan($participations_per_time_span)
    {
        $this->participations_per_time_span = $participations_per_time_span;
    }

    /**
     * @return mixed
     */
    public function getTimeSpan()
    {
        return $this->time_span;
    }

    /**
     * @param mixed $time_span
     */
    public function setTimeSpan($time_span)
    {
        $this->time_span = $time_span;
    }

}

src/Entity/ComparisonModule/Configuration/Website.php
<?php

namespace App\Entity\ComparisonModule\Configuration;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity
 * @ORM\Table(name="ComparisonModule_Website")
 */
class Website
{
    public function __construct()
    {
        $this->shown = 0;
    }

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }


    /**
     * @ORM\Column(type="string", unique=true, length=254)
     */
    private $website_name;

    /**
     * @return mixed
     */
    public function getWebsiteName()
    {
        return $this->website_name;
    }

    /**
     * @param mixed $website_name
     */
    public function setWebsiteName($website_name)
    {
        $this->website_name = $website_name;
    }


    /**
     * @ORM\Column(type="text")
     */
    private $website_url;

    /**
     * @return mixed
     */

    public function getWebsiteURL()
    {
        return $this->website_url;
    }

    /**
     * @param mixed $website_url
     */
    public function setWebsiteURL($website_url)
    {
        $this->website_url = $website_url;
    }


    /**
     * @ORM\Column(type="integer")
     */
    private $shown;

    /**
     * @return mixed
     */

    public function getShown()
    {
        return $this->shown;
    }

    /**
     * @param mixed $shown
     */
    public function setShown($shown)
    {
        $this->shown = $shown;
    }


    /**
     * @ORM\Column(type="boolean")
     */
    private $is_base_website;

    /**
     * @return mixed
     */

    public function getIsBaseWebsite()
    {
        return $this->is_base_website;
    }

    /**
     * @param mixed $is_base_website
     */
    public function setIsBaseWebsite($is_base_website)
    {
        $this->is_base_website = $is_base_website;
    }

}

templates/comparison_module/configuration/live_config.html.twig
{% extends 'admin_base.html.twig' %}
{% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}

{% block content %}

<div class="row mt-2">
    <div class="col-lg-12">

        {{ form_start(form) }}
        <h5>Button Labeling</h5>
        <div class="form-group row">
            {{ form_label(form.evalButton_left) }}
            <div class="col-sm-3">
                {{ form_widget(form.evalButton_left) }}
            </div>
            {{ form_label(form.evalButton_right) }}
            <div class="col-sm-3">
                {{ form_widget(form.evalButton_right) }}
            </div>
        </div>

        <div class="form-group row">
            {{ form_label(form.allowTie) }}
            <div class="col-sm-3">
                {{ form_widget(form.allowTie) }}
            </div>
        </div>
        <div id="app_configuration_middleButton" class="row">
            {{ form_label(form.middleButton) }}
            <div class="col-sm-3">
                {{ form_widget(form.middleButton) }}
            </div>
        </div>

        <hr>

        <h5>Randomization</h5>
        <div class="form-group row">
            {{ form_label(form.useBaseWebsite) }}
            <div class="col-sm-10">
                {{ form_widget(form.useBaseWebsite) }}
            </div>
        </div>
        <div  id="app_configuration_randomization_div">
            <div class="form-group row">
                <div class="col-sm-10">
                    {{ form_widget(form.randomization) }}
                </div>
            </div>
            <div id="app_configuration_document_order" class="form-group row">
                {{ form_label(form.documentOrder) }}
                {{ form_widget(form.documentOrder) }}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                {{ form_widget(form.randomization_participation) }}
            </div>
        </div>

        <hr>

        <h5>Cookie settings</h5>
        <div class="form-group row">
            {{ form_label(form.cookie_name) }}
            <div class="col-sm-4">
                {{ form_widget(form.cookie_name) }}
            </div>
            {{ form_label(form.cookie_expires) }}
            <div class="col-sm-4">
                {{ form_widget(form.cookie_expires) }}
            </div>
        </div>
        <div class="form-group row">
            {{ form_label(form.participations_per_time_span) }}
            <div class="col-sm-4">
                {{ form_widget(form.participations_per_time_span) }}
            </div>
            {{ form_label(form.time_span) }}
            <div class="col-sm-4">
                {{ form_widget(form.time_span) }}
            </div>
        </div>

        {{ form_widget(form.submit) }}
        {{ form_end(form) }}

    </div>
</div>

{% endblock %}

{% block javascripts %}
        <script type="text/javascript" src="{{ asset('js/comparison_module_general_config.js')}}"></script>
{% endblock %}

templates/comparison_module/configuration/standalone_config.html.twig
{% extends 'admin_base.html.twig' %}
{% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}


{% block content %}

<div class="row mt-2">
    <div class="col-lg-12">

        {{ form_start(form) }}
        <h5>Presentation</h5>
        <div class="form-group row">
            {{ form_label(form.presentationMode) }}
            <div class="col-sm-3">
                {{ form_widget(form.presentationMode) }}
            </div>
        </div>
        <div id="app_configuration_url" class="form-group row">
            {{ form_label(form.url) }}
            <div class="col-sm-10">
                {{ form_widget(form.url) }}
            </div>
        </div>
        <div id="app_configuration_presentationFields" class="form-group row">
            {{ form_label(form.presentationFields) }}
            <div class="col-lg-2">
                {{ form_widget(form.presentationFields) }}
            </div>

            <div class="col-lg-8">
                <div class="col-lg-12">
                    <i>Field names</i>
                    <div id="app_configuration_presentationFieldName_1" class="form-group row">
                        {{ form_label(form.presentationFieldName_1) }}
                        <div class="col-lg-5">
                            {{ form_widget(form.presentationFieldName_1) }}
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div id="app_configuration_presentationFieldName_2" class="form-group row">
                        {{ form_label(form.presentationFieldName_2) }}
                        <div class="col-lg-5">
                            {{ form_widget(form.presentationFieldName_2) }}
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div id="app_configuration_presentationFieldName_3" class="form-group row">
                        {{ form_label(form.presentationFieldName_3) }}
                        <div class="col-lg-5">
                            {{ form_widget(form.presentationFieldName_3) }}
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div id="app_configuration_presentationFieldName_4" class="form-group row">
                        {{ form_label(form.presentationFieldName_4) }}
                        <div class="col-lg-5">
                            {{ form_widget(form.presentationFieldName_4) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr>

        <h5>Button Labeling</h5>
        <div class="form-group row">
            {{ form_label(form.evalButton_left) }}
            <div class="col-sm-3">
                {{ form_widget(form.evalButton_left) }}
            </div>
            {{ form_label(form.evalButton_right) }}
            <div class="col-sm-3">
                {{ form_widget(form.evalButton_right) }}
            </div>
        </div>
        <div class="form-group row">
            {{ form_label(form.allowTie) }}
            <div class="col-sm-3">
                {{ form_widget(form.allowTie) }}
            </div>
        </div>
        <div id="app_configuration_middleButton" class="row">
            {{ form_label(form.middleButton) }}
            <div class="col-sm-3">
                {{ form_widget(form.middleButton) }}
            </div>
        </div>

        <hr>

        <h5>Randomization</h5>
        <div class="form-group row">
            <div class="col-sm-3">
                {{ form_widget(form.groupBy) }}
            </div>
            <div id="app_configuration_group_by_options" class="col-sm-3">
                {{ form_widget(form.groupByCategory) }}
            </div>
        </div>
        <div id="app_configuration_randomization_div">
            <div class="form-group row">
                <div class="col-sm-3">
                    {{ form_widget(form.randomization) }}
                </div>
            </div>
            <div id="app_configuration_document_order" class="form-group row">
                {{ form_label(form.documentOrder) }}
                {{ form_widget(form.documentOrder) }}
            </div>
        </div>

        <hr>
        {{ form_widget(form.submit) }}
        {{ form_end(form) }}

    </div>
</div>

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/comparison_module_general_config.js')}}"></script>
{% endblock %}

templates/comparison_module/configuration/website_config.html.twig
{%  extends 'admin_base.html.twig' %}
{% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}

{% block content %}

    <div class="row mt-2">
        <div class="col-lg-12">
            <h5>Websites</h5>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>URL</th>
                    <th>Shown</th>
                    <th></th>
                    {% if use_base_website %}
                        <th></th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for item in results %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.websiteName }}</td>
                        <td>{{ item.websiteURL }}</td>
                        <td>{{ item.shown }}</td>
                        <td>
                            <a class='btn btn-danger text-white' data-toggle="modal" data-target="#deletionModal{{ item.id }}">Delete</a>
                        </td>
                        {% if use_base_website %}
                            <td>
                                <a class='btn {% if item.isBaseWebsite %}btn-success{% else %}btn-warning{% endif %} text-white' href="{{ path('setWebsiteConfiguration', {'change_base': item.id}) }}">Base Website</a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-lg-12">
            <h5>Add a website</h5>
            {{ form_start(form) }}
            {{ form_row(form.website_name) }}
            {{ form_row(form.website_url) }}
            {{ form_widget(form.submit) }}
            {{ form_end(form) }}
        </div>
    </div>


    <!-- Modals -->
    {% for item in results %}
        <div class="modal fade" id="deletionModal{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="deletionModalLabel{{ item.id }}" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deletionModalLabel{{ item.id }}">Do you really want to delete this website?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <em>This action can not be undone!</em>
                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-secondary text-white" data-dismiss="modal" aria-label="Close">No!</a>
                        <a type="button" class="btn btn-danger text-white" href="{{ path('setWebsiteConfiguration', {'delete': item.id}) }}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}